/*
 * Description: Ptogram that generates random number and asks the user to guess it.
 * Name: Luciana Seljak
 * File name: NumberGuessingGame.cpp
 *
 */

#include <iostream>
#include <iomanip>
#include <ctime>
#include <cstdlib>
using namespace std;

int main ()
{

int randomNumber; 	   //Random number generated by program
int userGuess;			   //User guess
int totalGuesses = 0;		   //Number of guesses that user makes


   cout << "I'm guessing of a number.\n" << "Can you guess what it is? ";
   cin >> userGuess;

   srand(time(0));
   randomNumber = rand()%10;

     
        do{
	if(userGuess < randomNumber)
           {
		cout << "Sorry, that's too low.\n" << "Guess again: ";
		cin >> userGuess;
		totalGuesses++;
           } 
   
        else if(userGuess > randomNumber)
    	   {
		cout << "Sorry, that's too high.\n" << "Guess again: ";
		cin >> userGuess;
		totalGuesses++;
    	   } 
   	}while(userGuess != randomNumber);

	if(userGuess == randomNumber){
                totalGuesses++;
		cout << endl;
		cout << "Congratulations! You guessed it!" << endl;
                cout << "I was thinking of the number " << randomNumber << endl;
                cout << endl;
                cout << "The number of guesses is " << totalGuesses;
                cout << endl;
           }

     
return 0;
}
   		
// Sample Run
/*
------
I'm guessing of a number.
Can you guess what it is? 4
Sorry, that's too high.
Guess again: 2

Congratulations! You guessed it!
I was thinking of the number 2

The number of guesses is 2

------

I'm guessing of a number.
Can you guess what it is? 4
Sorry, that's too high.
Guess again: 2
Sorry, that's too high.
Guess again: 1
Sorry, that's too high.
Guess again: 0

Congratulations! You guessed it!
I was thinking of the number 0

The number of guesses is 4

-----

I'm guessing of a number.
Can you guess what it is? 8
Sorry, that's too low.
Guess again: 9

Congratulations! You guessed it!
I was thinking of the number 9

The number of guesses is 2


*/
